# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Water My Plants' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Water My Plants
pod 'Firebase/Core'
 pod 'Firebase/Database'
 pod 'Firebase/Auth'
 pod 'Firebase/Storage'
target 'Water My PlantsTests' do
 inherit! :search_paths
 # Pods for testing
 pod 'Firebase/Core'
 pod 'Firebase/Database'
 pod 'Firebase/Auth'
 pod 'Firebase/Storage'
 end
target 'Water My PlantsUITests' do
 inherit! :search_paths
 # Pods for testing
pod 'Firebase/Core'
 pod 'Firebase/Database'
 pod 'Firebase/Auth'
 pod 'Firebase/Storage'
end
end
